[yoonalc] solve-1-1: 2665. Counter II
cys-alchera/NO_Algo_NO_Gain pull request #2
Opened 2023-05-09 15:00 UTC by yoonalc

### 문제
[LINK](https://leetcode.com/problems/counter-ii/)

### Runtime/Memory
Runtime 81ms Beats 12.01%
Memory 45.6MB Beats 42.76%

### typescript 개발환경 세팅
[LINK](https://github.com/cys-alchera/NO_Algo_NO_Gain/wiki/webstorm%EC%97%90-typescript-%EB%94%94%EB%B2%84%EA%B9%85,-%ED%85%8C%EC%8A%A4%ED%8A%B8-%EA%B0%9C%EB%B0%9C%ED%99%98%EA%B2%BD-%EC%84%B8%ED%8C%85)

2023-05-09 15:25 UTC, phc-alchera requested changes
해당 문제 풀이에 대한 성능표 첨부 해주시면 좋을 것 같습니다!
(Runtime ##%, beats ##%,  Memory ##%, beats ##%)

2023-05-09 23:42 UTC, cys-alchera commented
@yoonalc 님, 풀이 주석에 성능 관련해서 넣어주세요.

2023-05-09 23:46 UTC, cys-alchera requested changes
코드 상에 성능 첨부 부탁드립니다~

2023-05-10 04:06 UTC, cys-alchera approved these changes

2023-05-10 04:06 UTC, cys-alchera commented on leetcode_2665/yoonalc.ts
> -// Memory 45.6 MB [42.76%]
고생 많으셨습니다. C++로도 풀어주세용. :last_quarter_moon_with_face:

2023-05-12 05:50 UTC, phc-alchera approved these changes
확인 했습니다! 고생하셨습니다.

2023-05-12 05:50 UTC, merged